version: '3'


services:
  db:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_DB=target_django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  tunnel:
    build: 
      context: ./tunnel
      dockerfile: Dockerfile
    environment:
       - FLASK_APP=./tunnel/tunnel.py
       - TAKION_IP=38.32.100.58
       - TAKION_PORT=15500
    command: pipenv run flask run --host=0.0.0.0 -p 9002
    volumes:
      - .:/code
    ports:
      - "9002:9002"
  web:
    build: .
    command: pipenv run python manage.py migrate
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    depends_on:
      - tunnel
