# Generated by Django 3.0.2 on 2020-07-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='totally_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
