# Generated by Django 3.0.2 on 2020-08-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0002_feature_totally_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flip_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='actors',
            field=models.ManyToManyField(related_name='features', to='django_feature_flip.Actor'),
        ),
    ]
