# Generated by Django 3.0.2 on 2020-07-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='features',
        ),
        migrations.AddField(
            model_name='feature',
            name='groups',
            field=models.ManyToManyField(related_name='features', to='django_feature_flip.Group'),
        ),
    ]
