# Generated by Django 3.0.2 on 2020-07-31 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0003_feature_time_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='time_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
