# Generated by Django 3.0.2 on 2020-08-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0003_group'),
        ('django_feature_flip', '0003_auto_20200803_1525'),
    ]

    operations = [
    ]
