# Generated by Django 3.0.2 on 2020-08-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0003_group'),
        ('django_feature_flip', '0004_auto_20200731_1926'),
    ]

    operations = [
    ]
