# Generated by Django 3.0.2 on 2020-08-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0004_auto_20200731_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
