# Generated by Django 3.0.2 on 2020-08-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0005_auto_20200813_1925'),
        ('django_feature_flip', '0004_auto_20200731_1926'),
    ]

    operations = [
    ]
