# Generated by Django 3.0.2 on 2020-08-11 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_feature_flip', '0005_merge_20200811_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='actors_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
